name: Build & Release FoundryVTT Module

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Zip & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Auto-increment patch version
        id: bump
        run: |
          FILE="module.json"
          VERSION=$(jq -r '.version' $FILE)
          IFS='.' read -r major minor patch <<< "$VERSION"
          patch=$((patch + 1))
          NEW_VERSION="${major}.${minor}.${patch}"
          jq ".version = \"$NEW_VERSION\" |
              .download = \"https://github.com/Ever-Onward-Games/pf1e-parallel-leveling/releases/download/v$NEW_VERSION/pf1e-parallel-leveling.zip\" |
              .manifest = \"https://raw.githubusercontent.com/Ever-Onward-Games/pf1e-parallel-leveling/main/module.json\"
          " $FILE > tmp.json && mv tmp.json $FILE

          echo "MODULE_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit bumped version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add module.json
          git commit -m "chore: bump version to v${{ env.MODULE_VERSION }}"
          git push

      - name: Create ZIP archive
        run: |
          mkdir package
          cp -r scripts styles module.json LICENSE README.md package/
          cd package && zip -r ../pf1e-parallel-leveling.zip . && cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.MODULE_VERSION }}
          name: Pf1e Parallel Leveling v${{ env.MODULE_VERSION }}
          files: |
            pf1e-parallel-leveling.zip
            module.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
